name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: first make
        continue-on-error: true
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make

      - name: first make
        continue-on-error: true
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
            biber article
            touch article.tex
            make
            touch article.tex
            make

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: article.pdf          