---
name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
          - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pyyaml
      - name: Update metadata
        run: |
          python yaml-to-latex.py        

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: article.tex