name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            python -m pip install --upgrade pip
            pip install pyyaml
            apk add make
            make

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: article.pdf          