name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' #install the python needed
      - name: Install dependencies and convert metadata
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          python yaml-to-latex.py -o metadata.tex      

      - name: first make
        continue-on-error: true
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make

      - name: first make
        continue-on-error: true
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
            biber article
            touch article.tex
            make
            touch article.tex
            make

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: article.pdf          

      - name: commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add article.pdf metadata.tex
          git commit -m 'Latexed PDF' || echo "No changes to commit"
          git push origin || echo "No changes to commit"                    